export type ToolStatus = "Standards-based" | "Planning estimate";
export type ToolMeta = { standard:string; version:string; range:string; assumptions:string; reviewed:string; status:ToolStatus; technicalOwner:string; reviewLevel:string };

const reviewed="28 August 2026";
const technicalOwner="WaveKit maintainer · suwatchaiT";
const reviewLevel="Maintainer formula review; independent SME validation pending";
const categoryDefaults:Record<string,ToolMeta>={
  "RF Planning":{standard:"ITU-R propagation and radio-link engineering methods",version:"Current linked recommendations; simplified browser implementation",range:"Use only within the limits stated by the selected model and input fields.",assumptions:"Nominal equipment values, consistent units and a stationary radio path unless the tool says otherwise.",reviewed,status:"Planning estimate",technicalOwner,reviewLevel},
  Cellular:{standard:"3GPP radio-access specifications",version:"Referenced 3GPP releases and band tables shown on the tool",range:"GSM, LTE and NR ranges supported by the displayed band/raster tables.",assumptions:"Nominal physical-layer configuration; implementation and regional band support may differ.",reviewed,status:"Standards-based",technicalOwner,reviewLevel},
  Antenna:{standard:"Classical antenna theory and referenced ITU-R/IEEE methods",version:"Analytical planning model",range:"Far-field, narrowband or free-space conditions unless explicitly stated otherwise.",assumptions:"Ideal geometry and nominal antenna data; mounting, coupling, clutter and manufacturing tolerances are excluded.",reviewed,status:"Planning estimate",technicalOwner,reviewLevel},
  "Wi-Fi":{standard:"IEEE 802.11 channelization and PHY concepts",version:"802.11 through 802.11be where applicable",range:"2.4 GHz, 5 GHz and 6 GHz values exposed by the tool.",assumptions:"Regulatory availability, permitted power and channel width must be verified for the deployment country.",reviewed,status:"Standards-based",technicalOwner,reviewLevel},
  "IP Calculator":{standard:"IETF RFC addressing and subnetting conventions",version:"IPv4/IPv6 standards referenced on the tool",range:"IPv4 0.0.0.0–255.255.255.255 or IPv6 /0–/128 as applicable.",assumptions:"Canonical CIDR arithmetic; routing policy, firewall behavior and platform-specific reservations are excluded.",reviewed,status:"Standards-based",technicalOwner,reviewLevel},
};

const overrides:Record<string,Partial<ToolMeta>>={
  "channel-frequency":{standard:"3GPP TS 45.005, TS 36.101 and TS 38.104",version:"Formula review against TS 36.101 §5.7.3 and NR global raster",range:"Supported GSM ARFCN, LTE EARFCN and NR-ARFCN ranges shown after selecting a technology and direction.",assumptions:"The selected channel belongs to the selected band; regional licensing and equipment support are not inferred.",reviewLevel:"Maintainer formula review completed; full band-table SME validation pending"},
  "resource-blocks":{standard:"3GPP TS 36.211 and TS 38.104",version:"NR table review against TS 38.104 V17.13.0 §5.3.2",range:"LTE 1.4–20 MHz; NR combinations available in the selected SCS/bandwidth table.",reviewLevel:"Maintainer table review completed; independent SME validation pending"},
  "lte-resource-grid":{standard:"3GPP TS 36.211",version:"LTE downlink/uplink resource-grid planning view",range:"LTE bandwidths 1.4–20 MHz and displayed FDD/TDD configurations."},
  "nr-resource-grid":{standard:"3GPP TS 38.211 and TS 38.213",version:"NR resource-grid planning view",range:"Displayed FR1/FR2 numerologies, bandwidths and TDD patterns."},
  "maximum-cellular-speed":{standard:"3GPP LTE/NR physical-layer parameters",version:"Planning equation review using standardized PRB tables",status:"Planning estimate",range:"LTE FDD/TDD and NR configurations exposed in the calculator.",assumptions:"Theoretical peak rate before scheduler, coding-rate, protocol, retransmission, RF and core-network losses.",reviewLevel:"Maintainer boundary review completed; MCS/TBS conformance validation pending"},
  "free-space-path-loss":{standard:"ITU-R P.525-5",version:"Recommendation P.525-5 (11/2024), equation 6",range:"Free-space line-of-sight paths at any positive frequency and distance entered.",assumptions:"Unobstructed isotropic propagation; excludes clutter, diffraction, reflection, weather and feeder losses.",reviewLevel:"Maintainer formula and reference-case review completed"},
  "link-budget":{standard:"ITU-R P.341 with referenced 3GPP transmitter/receiver parameters",version:"Deterministic MAPL planning chain reviewed 28 August 2026",range:"LTE and NR configurations exposed by the calculator.",assumptions:"Median deterministic budget; site-specific fading, interference and implementation margins require engineering review.",reviewLevel:"Maintainer formula review completed; independent RF-planning SME approval pending"},
  "fresnel-zone":{standard:"First Fresnel-zone geometry",range:"Any positive MHz frequency and positive d1/d2 path distances.",assumptions:"Straight line of sight and smooth-earth geometry; terrain and Earth curvature are not automatically profiled."},
  "thermal-noise":{standard:"Johnson–Nyquist thermal noise",range:"Positive bandwidth and physically meaningful temperature/noise-figure inputs."},
  "eirp":{standard:"Logarithmic RF power accounting",range:"Any internally consistent dBm, dB and dBi values.",assumptions:"Single transmit path; mismatch, antenna-pattern direction and regulatory averaging are excluded."},
  "cidr-tools":{standard:"IETF CIDR prefix arithmetic",range:"One valid IPv4 parent network, /0 through /32.",assumptions:"The entered address is normalized to its parent network before aligned child prefixes are generated."},
};

export function getToolMeta(slug:string,category:string):ToolMeta{return {...categoryDefaults[category],...overrides[slug]}}
