export const toolCatalog = [
  { slug: "channel-frequency", name: "Channel ↔ Frequency", category: "Cellular", summary: "Convert GSM ARFCN, LTE EARFCN and NR-ARFCN to frequency." },
  { slug: "resource-blocks", name: "Resource Block Calculator", category: "Cellular", summary: "Look up LTE and 5G NR resource blocks by bandwidth." },
  { slug: "lte-resource-grid", name: "LTE Resource Grid", category: "Cellular", summary: "Visualize LTE downlink physical channels across OFDM symbols and subcarriers." },
  { slug: "nr-resource-grid", name: "NR Resource Grid", category: "Cellular", summary: "Visualize NR slots, synchronization signals, control, data and reference resources." },
  { slug: "maximum-cellular-speed", name: "Maximum Cellular Speed", category: "Cellular", summary: "Estimate theoretical LTE FDD, LTE TDD and 5G NR peak throughput." },
  { slug: "free-space-path-loss", name: "Free-Space Path Loss", category: "RF Planning", summary: "Calculate ideal line-of-sight propagation loss." },
  { slug: "link-budget", name: "Link Budget", category: "RF Planning", summary: "Estimate received power and available fade margin." },
  { slug: "fresnel-zone", name: "Fresnel Zone", category: "RF Planning", summary: "Find first Fresnel-zone radius and clearance." },
  { slug: "thermal-noise", name: "Thermal Noise Floor", category: "RF Planning", summary: "Calculate receiver noise floor from bandwidth and noise figure." },
  { slug: "eirp", name: "EIRP Calculator", category: "RF Planning", summary: "Combine transmitter power, cable loss and antenna gain." },
  { slug: "antenna-coverage", name: "Antenna Coverage & Downtilt", category: "Antenna", summary: "Estimate boresight and vertical-beam coverage limits." },
  { slug: "radiation-pattern", name: "Sector Radiation Pattern", category: "Antenna", summary: "Model horizontal and vertical sector-antenna gain patterns." },
  { slug: "array-beamforming", name: "Antenna Array & Beamforming", category: "Antenna", summary: "Estimate array gain, beamwidth and grating-lobe risk." },
  { slug: "gain-aperture", name: "Antenna Gain ↔ Aperture", category: "Antenna", summary: "Convert antenna gain and effective aperture at any frequency." },
  { slug: "dish-design", name: "Parabolic Dish Design", category: "Antenna", summary: "Calculate dish gain, beamwidth, aperture and focal length." },
  { slug: "near-far-field", name: "Near/Far-Field Distance", category: "Antenna", summary: "Calculate reactive, radiating and Fraunhofer field boundaries." },
  { slug: "polarization-loss", name: "Polarization Mismatch Loss", category: "Antenna", summary: "Estimate loss between linear and circular polarizations." },
  { slug: "mimo-spacing", name: "Antenna Diversity & MIMO Spacing", category: "Antenna", summary: "Estimate wavelength-based antenna separation guidance." },
  { slug: "pim-finder", name: "Passive Intermodulation Finder", category: "Antenna", summary: "Find odd-order intermodulation products inside a receive band." },
  { slug: "feeder-loss", name: "Tower Line & Feeder Loss", category: "Antenna", summary: "Estimate cable, jumper and connector loss at operating frequency." },
  { slug: "power-converter", name: "RF Power Converter", category: "RF Planning", summary: "Convert between dBm, dBW, watts and milliwatts." },
  { slug: "wifi-channel", name: "Wi-Fi Channel Reference", category: "Wi-Fi", summary: "Convert 2.4, 5 and 6 GHz Wi-Fi channels to center frequency." },
  { slug: "wifi-airtime", name: "Wi-Fi Airtime", category: "Wi-Fi", summary: "Estimate transmission airtime from payload and PHY rate." },
  { slug: "ipv4-subnet", name: "IPv4 Subnet Calculator", category: "IP Calculator", summary: "Calculate network, broadcast, masks, range and usable hosts." },
  { slug: "ipv6-subnet", name: "IPv6 Subnet Calculator", category: "IP Calculator", summary: "Inspect IPv6 prefixes, ranges and address capacity." },
  { slug: "vlsm-planner", name: "VLSM Subnet Planner", category: "IP Calculator", summary: "Allocate different host requirements inside one IPv4 prefix." },
  { slug: "cidr-tools", name: "CIDR Split Calculator", category: "IP Calculator", summary: "Divide an IPv4 prefix into correctly aligned smaller subnets." },
  { slug: "ip-analyzer", name: "IP Address Analyzer", category: "IP Calculator", summary: "Identify address version, scope and special-use classification." },
  { slug: "ip-range", name: "IP Range Calculator", category: "IP Calculator", summary: "Convert an IPv4 start/end range into the smallest CIDR list." },
  { slug: "wildcard-mask", name: "Wildcard Mask Calculator", category: "IP Calculator", summary: "Convert between IPv4 CIDR, subnet mask and ACL wildcard." },
  { slug: "ip-converter", name: "IPv4 Integer/Binary/Hex", category: "IP Calculator", summary: "Convert IPv4 addresses into integer, binary and hexadecimal forms." },
  { slug: "ipv6-format", name: "IPv6 Expand & Compress", category: "IP Calculator", summary: "Convert between full and canonical compressed IPv6 notation." },
  { slug: "mtu-mss", name: "MTU, MSS & Packet Overhead", category: "IP Calculator", summary: "Estimate payload and MSS through common tunnel encapsulations." },
  { slug: "dhcp-planner", name: "DHCP Pool Planner", category: "IP Calculator", summary: "Plan gateway, exclusions and dynamic IPv4 address pools." },
  { slug: "network-overlap", name: "Network Overlap Checker", category: "IP Calculator", summary: "Detect overlapping, contained and duplicate IPv4 prefixes." },
] as const;

export const categories = ["RF Planning", "Cellular", "Antenna", "Wi-Fi", "IP Calculator"] as const;
