type Explain = {
  formula: string;
  caption: string;
  variables: [string,string][];
  flow: [string,string,string];
  steps: string[];
  visual: "link"|"spectrum"|"antenna"|"blocks"|"convert";
};

const guides: Record<string,Explain> = {
  "channel-frequency": { formula:"f = F₀ + Δf × (N − N₀)  ⇄  N = N₀ + (f − F₀) ÷ Δf", caption:"Convert in either direction between channel numbering and the applicable frequency raster.", variables:[["f","center frequency"],["F₀","band reference frequency"],["Δf","channel raster spacing"],["N","ARFCN, EARFCN or NR-ARFCN"],["N₀","band reference channel"]], flow:["Channel or frequency","Technology raster","Frequency or channel"], steps:["Choose GSM, LTE or 5G NR.","Choose the conversion direction and enter the known value.","Apply the raster and return the nearest valid channel when reversing."], visual:"spectrum" },
  "resource-blocks": { formula:"Nᴿᴮ = lookup(BW, SCS)", caption:"Standards define the usable PRB count for each bandwidth and subcarrier spacing.", variables:[["Nᴿᴮ","number of physical resource blocks"],["BW","nominal channel bandwidth"],["SCS","subcarrier spacing; LTE uses 15 kHz here"]], flow:["Bandwidth","SCS table","Usable PRBs"], steps:["Select LTE or NR numerology.","Enter a standardized channel bandwidth.","Read the corresponding usable PRB count."], visual:"blocks" },
  "lte-resource-grid": { formula:"1 RE = Δf × Tsymbol  ·  1 PRB = 12 subcarriers × 1 slot", caption:"The LTE resource grid maps physical signals and channels onto subcarriers in frequency and OFDM symbols in time.", variables:[["RE","one resource element: one subcarrier for one OFDM symbol"],["PRB","12 consecutive 15 kHz subcarriers over one slot"],["CFI","number of leading OFDM symbols reserved for control"],["PCI","physical cell identity controlling reference-signal shifts"],["D / U / S","TDD downlink, uplink and special subframe types"]], flow:["LTE configuration","Channel mapping","Resource-element grid"], steps:["Select duplex mode, bandwidth and subframe.","Set cyclic prefix, antenna ports, PCI and control region.","Use the color grid to inspect physical-channel occupancy."], visual:"blocks" },
  "nr-resource-grid": { formula:"Nslot/frame = 10 × 2ᵘ  ·  μ = log₂(Δf ÷ 15 kHz)", caption:"The 5G NR grid changes its slot rate with numerology while each normal-CP slot retains 14 OFDM symbols.", variables:[["μ","NR numerology index"],["Δf","subcarrier spacing: 15, 30, 60 or 120 kHz"],["CORESET","time-frequency region carrying PDCCH"],["DM-RS","demodulation reference signal associated with data"],["SS/PBCH","synchronization-signal and broadcast-channel block"]], flow:["BWP + numerology","Slot channel mapping","NR resource grid"], steps:["Select SCS, bandwidth and slot direction.","Configure CORESET, DM-RS and optional SS/PBCH presence.","Inspect resource-element occupancy in the central carrier region."], visual:"blocks" },
  "maximum-cellular-speed": { formula:"R = Nᴿᴮ × 12 × Nsym/s × Qₘ × layers × carriers × (1 − OH)", caption:"Peak PHY throughput combines usable radio resources, duplex time, modulation, MIMO and carrier aggregation before an explicit overhead allowance.", variables:[["Nᴿᴮ","standard physical resource blocks"],["Nsym/s","usable OFDM symbols per second, including duplex allocation"],["Qₘ","modulation order: 2, 4, 6 or 8 bits/symbol"],["layers","simultaneous MIMO spatial layers"],["OH","control, pilot and implementation overhead fraction"]], flow:["Bandwidth + duplex","Modulation × MIMO × CA","Peak net speed"], steps:["Choose LTE FDD, LTE TDD or 5G NR and the link direction.","Select standardized bandwidth, time allocation and modulation.","Scale by MIMO layers and carriers, then subtract the planning overhead."], visual:"blocks" },
  "free-space-path-loss": { formula:"PL = model(f, d, hBS, hUT, environment)", caption:"Choose the propagation model whose frequency, distance and deployment assumptions match the radio link.", variables:[["PL","median path loss in dB"],["f","operating frequency"],["d","Tx-to-Rx distance"],["hBS, hUT","base-station and terminal heights"],["environment","LOS, urban, suburban, rural or street canyon"]], flow:["Link inputs","Applicable model","Median path loss"], steps:["Choose a model valid for the frequency band and environment.","Enter distance and the heights required by that model.","Review the active equation and confirm all validity limits."], visual:"link" },
  "link-budget": { formula:"MAPL = EIRP + Grx − Lrx − Srx − ΣMargins", caption:"The LTE/NR budget derives receiver sensitivity from allocated PRBs and required SINR, then reserves explicit environment and reliability margins.", variables:[["MAPL","maximum allowable path loss in dB"],["EIRP","conducted power − Tx loss + Tx antenna gain"],["Srx","thermal noise + NF + SINR + implementation loss"],["ΣMargins","penetration, body, shadow, fast-fade and interference margins"],["PRB × SCS","occupied receiver noise bandwidth"]], flow:["LTE / NR EIRP","Propagation + margins","Receiver sensitivity"], steps:["Define LTE/NR resource allocation and link direction.","Calculate EIRP and receiver sensitivity independently.","Subtract environmental margins to obtain MAPL."], visual:"link" },
  "fresnel-zone": { formula:"r₁ = 547.72 √(d₁d₂ ÷ f(d₁+d₂))", caption:"The first Fresnel-zone radius is calculated at point P along the radio path and is largest at the midpoint.", variables:[["r₁","first-zone radius at point P, in metres"],["d₁","distance from transmitter to point P, in kilometres"],["d₂","distance from point P to receiver, in kilometres"],["f","frequency in megahertz"],["D","total path distance: d₁ + d₂"]], flow:["Tx — distance d₁","Point P / radius r₁","distance d₂ — Rx"], steps:["Choose point P where clearance will be evaluated.","Enter Tx-to-P distance d₁ and P-to-Rx distance d₂.","Keep practical clearance near 60% or more of r₁."], visual:"link" },
  "thermal-noise": { formula:"N = −174 + 10 log₁₀(B) + NF", caption:"Room-temperature noise density is scaled by bandwidth and receiver noise figure.", variables:[["N","receiver noise floor in dBm"],["−174","thermal noise density in dBm/Hz at 290 K"],["B","noise bandwidth in hertz"],["NF","receiver noise figure in dB"]], flow:["Noise density","Bandwidth + NF","Noise floor"], steps:["Convert bandwidth to hertz.","Add the 10 log bandwidth term.","Add the receiver noise figure."], visual:"spectrum" },
  "eirp": { formula:"EIRP = Pᵀˣ − Lfeeder + Gantenna", caption:"EIRP represents transmitted power referenced to an ideal isotropic antenna.", variables:[["Pᵀˣ","radio output power in dBm"],["Lfeeder","cable and connector loss in dB"],["Gantenna","antenna gain in dBi"]], flow:["Radio power","Feeder + antenna","Radiated EIRP"], steps:["Enter radio output power.","Subtract loss before the antenna port.","Add antenna gain relative to isotropic."], visual:"antenna" },
  "wavelength": { formula:"λ = c ÷ f", caption:"Wavelength is propagation speed divided by frequency.", variables:[["λ","wavelength in metres"],["c","speed of light, 299,792,458 m/s"],["f","frequency in hertz"],["λ/2, λ/4","common half- and quarter-wave dimensions"]], flow:["Frequency","Speed of light ÷ f","Element length"], steps:["Convert frequency from MHz to hertz.","Divide the speed of light by frequency.","Scale λ for half- or quarter-wave elements."], visual:"antenna" },
  "downtilt": { formula:"D = h ÷ tan(θ)", caption:"A level-terrain geometric estimate of where the antenna boresight meets the ground.", variables:[["D","horizontal intersection distance"],["h","antenna height above target ground"],["θ","total electrical plus mechanical downtilt"]], flow:["Antenna height","Downtilt angle","Ground intercept"], steps:["Enter antenna height above ground.","Enter total boresight downtilt.","Solve the right triangle for horizontal distance."], visual:"antenna" },
  "antenna-coverage": {formula:"D = (hBS − hUE) ÷ tan θ",caption:"Downtilt and vertical beamwidth define the approximate boresight, near edge and far edge on level terrain.",variables:[["hBS","base antenna height"],["hUE","target height"],["θ","boresight downtilt"],["θ3dB","vertical half-power beamwidth"]],flow:["Height + beam","Vertical geometry","Coverage footprint"],steps:["Enter antenna and target heights.","Set combined mechanical and electrical tilt.","Apply half the vertical beamwidth to find near and far edges."],visual:"antenna"},
  "radiation-pattern": {formula:"A = min[12(φ/φ3dB)² + 12(θ/θ3dB)², Am]",caption:"A sector reference pattern estimates gain reduction away from antenna boresight.",variables:[["φ, θ","horizontal and vertical off-axis angles"],["φ3dB, θ3dB","half-power beamwidths"],["Am","maximum attenuation or front-to-back cap"],["Gmax","peak antenna gain"]],flow:["Beam parameters","Off-axis attenuation","Directional gain"],steps:["Enter peak gain and beamwidths.","Choose a pattern plane and angle.","Subtract pattern attenuation from peak gain."],visual:"antenna"},
  "array-beamforming": {formula:"Garray = 10 log₁₀(N)",caption:"Coherent elements increase ideal array gain and narrow the main beam, subject to spacing and steering limits.",variables:[["N","total radiating elements"],["d","element spacing in wavelengths"],["θs","electronic steering angle"],["HPBW","approximate half-power beamwidth"]],flow:["Array geometry","Phase steering","Gain + beamwidth"],steps:["Set frequency and array dimensions.","Enter normalized spacing and steering angle.","Check array gain, beamwidth and grating-lobe warning."],visual:"antenna"},
  "gain-aperture": {formula:"Ae = Gλ² ÷ 4π",caption:"Effective collecting area depends on linear antenna gain and wavelength.",variables:[["Ae","effective aperture"],["G","linear antenna gain"],["λ","wavelength"],["η","aperture efficiency"]],flow:["Gain + frequency","Effective aperture","Physical area"],steps:["Convert dBi gain to linear gain.","Calculate wavelength from frequency.","Divide effective aperture by efficiency for physical area."],visual:"antenna"},
  "dish-design": {formula:"G = η(πD/λ)²",caption:"Parabolic-reflector size, frequency and efficiency determine gain and beamwidth.",variables:[["D","dish diameter"],["η","aperture efficiency"],["λ","wavelength"],["F/D","focal-length to diameter ratio"]],flow:["Dish geometry","Aperture efficiency","Gain + beamwidth"],steps:["Enter frequency and reflector diameter.","Set aperture efficiency and F/D ratio.","Calculate gain, beamwidth and focal length."],visual:"antenna"},
  "near-far-field": {formula:"Rfar = 2D² ÷ λ",caption:"Antenna dimension and wavelength define the approximate electromagnetic field regions.",variables:[["D","largest antenna dimension"],["λ","wavelength"],["Rreactive","reactive near-field boundary"],["Rfar","Fraunhofer far-field boundary"]],flow:["Size + wavelength","Field boundaries","Measurement distance"],steps:["Enter frequency and largest antenna dimension.","Calculate reactive and radiating near-field limits.","Use the Fraunhofer boundary for far-field planning."],visual:"antenna"},
  "polarization-loss": {formula:"Lpol = −20 log₁₀|cos ψ|",caption:"Misaligned or incompatible polarizations reduce received power even when the antennas otherwise align.",variables:[["ψ","linear polarization mismatch angle"],["Lpol","polarization mismatch loss"],["XPD","cross-polar discrimination"],["RHCP/LHCP","circular polarization handedness"]],flow:["Tx polarization","Alignment / handedness","Mismatch loss"],steps:["Choose the polarization pair.","Enter angle or assumed XPD where applicable.","Include the resulting loss in the link budget."],visual:"antenna"},
  "mimo-spacing": {formula:"Srecommended = kλ",caption:"A wavelength-based separation is a first planning check for diversity and MIMO antennas.",variables:[["S","recommended antenna separation"],["k","environment-dependent spacing factor"],["λ","wavelength"],["f","operating frequency"]],flow:["Frequency + environment","Wavelength factor","Antenna spacing"],steps:["Enter operating frequency.","Choose the propagation environment.","Compare recommended and custom wavelength spacing."],visual:"antenna"},
  "pim-finder": {formula:"fPIM = |m·f₁ ± n·f₂|",caption:"Odd-order passive intermodulation products can fall into a sensitive receive band.",variables:[["f₁, f₂","transmit carriers"],["m, n","integer mixing coefficients"],["m+n","third, fifth or seventh order"],["Rx band","frequency window checked for hits"]],flow:["Two transmit carriers","Odd-order mixing","Receive-band hits"],steps:["Enter two transmit frequencies.","Define the receive-band limits.","Inspect third-, fifth- and seventh-order products inside the band."],visual:"spectrum"},
  "feeder-loss": {formula:"Ltotal = α(f)L + ΣLconnector + Ljumper",caption:"Tower-line loss combines frequency-specific cable attenuation, length, connectors and jumpers.",variables:[["α(f)","cable attenuation at operating frequency"],["L","main feeder length"],["Lconnector","individual connector loss"],["Ltotal","total insertion loss"]],flow:["Cable + connectors","Insertion losses","Delivered power"],steps:["Enter cable loss from its datasheet at frequency.","Apply the main cable length and connector losses.","Review total loss and percentage of power delivered."],visual:"antenna"},
  "ipv4-subnet": {formula:"network = address AND mask",caption:"CIDR prefix bits divide an IPv4 address into network and host portions.",variables:[["/p","CIDR prefix length"],["mask","32-bit subnet mask"],["host bits","32 − p"],["broadcast","last address in the subnet"]],flow:["IPv4 + prefix","Bitwise subnet","Range + hosts"],steps:["Enter an IPv4 address.","Select the CIDR prefix.","Read network, masks, broadcast and usable range."],visual:"blocks"},
  "ipv6-subnet": {formula:"network = address AND /prefix",caption:"An IPv6 prefix identifies the network while the remaining bits identify addresses within it.",variables:[["prefix","leading network bits"],["host bits","128 − prefix"],["first","all host bits zero"],["last","all host bits one"]],flow:["IPv6 + prefix","128-bit mask","Prefix range"],steps:["Enter compressed or expanded IPv6.","Select the prefix length.","Inspect canonical network and range."],visual:"blocks"},
  "vlsm-planner": {formula:"block size = next power of 2(hosts + 2)",caption:"VLSM assigns the largest host requirements first to minimize wasted IPv4 space.",variables:[["hosts","required usable addresses"],["block","power-of-two address allocation"],["prefix","32 − log₂(block)"],["parent","containing address range"]],flow:["Parent prefix","Largest-first allocation","VLSM plan"],steps:["Enter the parent network.","List required host counts.","Review allocated prefixes and capacity."],visual:"blocks"},
  "cidr-tools": {formula:"subnets = 2^(new prefix − old prefix)",caption:"A parent CIDR prefix can be divided into correctly aligned, equal-size child networks.",variables:[["old prefix","source network size"],["new prefix","requested child size"],["subnets","number of generated child prefixes"],["CIDR","classless network notation"]],flow:["Parent CIDR","Select child prefix","Aligned subnets"],steps:["Enter the parent IPv4 network.","Select its prefix and the new longer prefix.","Inspect the resulting child CIDR blocks."],visual:"blocks"},
  "ip-analyzer": {formula:"type = longest matching special-use prefix",caption:"Address classification is determined from assigned high-order IPv4 or IPv6 prefix bits.",variables:[["scope","where an address is valid"],["private","non-public address space"],["multicast","one-to-many destination"],["link-local","valid only on the local link"]],flow:["IP address","Prefix classification","Version + scope"],steps:["Enter IPv4 or IPv6.","Validate its notation.","Identify version, scope and representation."],visual:"convert"},
  "ip-range": {formula:"range = minimum aligned power-of-two CIDR blocks",caption:"An arbitrary IPv4 interval can be represented by the smallest set of aligned CIDR networks.",variables:[["start","first included address"],["end","last included address"],["alignment","valid network boundary"],["block","power-of-two CIDR range"]],flow:["Start + end","Aligned decomposition","CIDR list"],steps:["Enter an ascending IPv4 range.","Select the largest aligned block repeatedly.","Use the resulting minimal CIDR list."],visual:"blocks"},
  "wildcard-mask": {formula:"wildcard = 255.255.255.255 − subnet mask",caption:"An ACL wildcard is the bitwise inverse of its IPv4 subnet mask.",variables:[["mask bit 1","address bit must match"],["wildcard bit 1","address bit is ignored"],["prefix","count of network bits"],["ACL","access-control matching rule"]],flow:["CIDR prefix","Invert subnet mask","Wildcard mask"],steps:["Enter IPv4 and prefix.","Generate the subnet mask.","Invert every bit for the wildcard."],visual:"convert"},
  "ip-converter": {formula:"integer = a·256³ + b·256² + c·256 + d",caption:"The same 32 IPv4 bits can be represented as dotted decimal, integer, binary or hexadecimal.",variables:[["a–d","IPv4 octets"],["integer","unsigned 32-bit value"],["binary","32 individual bits"],["hex","eight hexadecimal digits"]],flow:["Dotted IPv4","32-bit value","Binary + hex"],steps:["Enter a valid IPv4 address.","Weight each octet by its byte position.","Display equivalent number formats."],visual:"convert"},
  "ipv6-format": {formula:"canonical = lowercase + longest zero-run compression",caption:"IPv6 canonical text removes leading zeros and compresses one longest consecutive zero run.",variables:[["hextet","16-bit hexadecimal group"],["::","one compressed zero run"],["expanded","eight four-digit hextets"],["canonical","recommended compact notation"]],flow:["IPv6 text","Expand + normalize","Canonical form"],steps:["Enter compressed or full IPv6.","Expand to eight hextets.","Compress the longest zero run."],visual:"convert"},
  "mtu-mss": {formula:"MSS = MTU − IP/TCP/tunnel headers",caption:"Encapsulation consumes packet bytes and reduces the payload that fits without fragmentation.",variables:[["MTU","maximum layer-3 packet size"],["MSS","maximum TCP data segment"],["overhead","protocol and tunnel headers"],["efficiency","payload divided by MTU"]],flow:["Path MTU","Subtract headers","Payload / MSS"],steps:["Enter the path MTU.","Choose protocol and tunnel stack.","Review MSS and payload efficiency."],visual:"blocks"},
  "dhcp-planner": {formula:"pool = usable subnet − gateway − exclusions",caption:"A DHCP pool must remain inside its subnet while reserving infrastructure and static addresses.",variables:[["gateway","router address"],["exclusions","reserved addresses"],["pool","dynamically assignable range"],["lease count","available dynamic addresses"]],flow:["Subnet + gateway","Reserve addresses","DHCP pool"],steps:["Enter subnet and gateway.","Reserve addresses from the beginning.","Review dynamic range and lease capacity."],visual:"blocks"},
  "network-overlap": {formula:"overlap when Astart ≤ Bend and Bstart ≤ Aend",caption:"Two prefixes conflict when their numeric address intervals intersect.",variables:[["start","network address"],["end","broadcast address"],["contained","one range fully inside another"],["duplicate","identical address ranges"]],flow:["CIDR list","Pairwise range check","Conflicts"],steps:["Enter one IPv4 CIDR per line.","Convert each to a numeric range.","Inspect all overlapping pairs."],visual:"blocks"},
  "power-converter": { formula:"P(W) = 10^((P(dBm) − 30) ÷ 10)", caption:"Logarithmic dBm values are converted to absolute power in watts.", variables:[["P(W)","power in watts"],["P(dBm)","power relative to one milliwatt"],["30","difference between dBW and dBm"]], flow:["dBm input","10ˣ conversion","Watts / mW"], steps:["Subtract 30 from the dBm value.","Divide the result by ten.","Raise ten to that exponent."], visual:"convert" },
  "wifi-channel": { formula:"fcenter = Fbase + 5 × channel", caption:"Wi-Fi channel centres normally sit on a 5 MHz numbering raster.", variables:[["fcenter","channel centre frequency in MHz"],["Fbase","band-specific base: 2407, 5000 or 5950 MHz"],["channel","IEEE channel number"],["Ch 14","special 2.4 GHz centre at 2484 MHz"]], flow:["Wi-Fi band","Channel raster","Center frequency"], steps:["Choose 2.4, 5 or 6 GHz.","Enter the channel number.","Apply the band base and 5 MHz raster."], visual:"spectrum" },
  "wifi-airtime": { formula:"t = (8 × payload bytes) ÷ PHY rate", caption:"An ideal payload-only estimate before MAC, PHY, contention and retry overhead.", variables:[["t","transmission time in seconds"],["payload","data length in bytes"],["8","bits per byte"],["PHY rate","gross link rate in bits per second"]], flow:["Payload bytes","Bits ÷ PHY rate","Ideal airtime"], steps:["Convert payload bytes into bits.","Convert PHY rate from Mbps to bit/s.","Divide bits by rate and report milliseconds."], visual:"blocks" },
};

function Visual({slug,kind,labels}:{slug:string;kind:Explain["visual"];labels:[string,string,string]}){
  const antenna=["antenna-coverage","radiation-pattern","array-beamforming","gain-aperture","dish-design","near-far-field","polarization-loss","mimo-spacing","feeder-loss"].includes(slug);
  const ip=["ipv4-subnet","ipv6-subnet","vlsm-planner","cidr-tools","ip-analyzer","ip-range","wildcard-mask","ip-converter","ipv6-format","dhcp-planner","network-overlap"].includes(slug);
  if(slug==="free-space-path-loss"||slug==="fresnel-zone")return <div className="technical-visual path-profile"><div className="tech-sky"><i/><i/><i/></div><div className="tech-tower tx"><b/><span>Base station</span></div><div className="tech-tower rx"><b/><span>UE / receiver</span></div><div className="tech-radio-path"><span>radio path</span></div><div className="tech-buildings">{[28,48,34,61,40,53,31].map((h,i)=><i key={i} style={{height:h}}/>)}</div><div className="tech-distance"><i/><span>distance d</span><i/></div><div className="tech-badges"><b>f · MHz</b><b>hBS · m</b><b>hUE · m</b><b>PL · dB</b></div></div>;
  if(slug==="link-budget")return <div className="technical-visual waterfall"><div className="waterfall-title"><b>POWER LEVEL THROUGH THE RADIO LINK</b><span>gain adds · loss subtracts</span></div>{[["Tx power",92,"+"],["Feeder",83,"−"],["Antenna",100,"+"],["Path loss",32,"−"],["Rx power",28,"="]].map(([name,width,sign])=><div className="waterfall-row" key={name}><span>{name}</span><i style={{width:`${width}%`}}/><b>{sign}</b></div>)}</div>;
  if(antenna)return <div className="technical-visual polar-tech"><div className="polar-rings"><i/><i/><i/><i/><b/></div><div className="polar-lobe main"/><div className="polar-lobe side one"/><div className="polar-lobe side two"/><div className="polar-label"><b>0° BORESIGHT</b><span>HPBW · gain · sidelobes</span></div></div>;
  if(slug==="mtu-mss")return <div className="technical-visual packet-tech"><div className="packet-label"><b>1500-byte packet</b><span>headers reduce usable payload</span></div><div className="packet-row"><i className="eth">Ethernet<small>14 B</small></i><i className="ip">IPv4<small>20 B</small></i><i className="tcp">TCP<small>20 B</small></i><i className="payload">Payload / MSS<small>1460 B</small></i></div><div className="packet-scale"><span>0</span><span>MTU</span></div></div>;
  if(ip)return <div className="technical-visual address-tech"><div className="address-head"><b>ADDRESS SPACE</b><span>network prefix and host allocation</span></div><div className="address-ruler"><i className="network">Network</i><i className="gateway">GW</i><i className="reserved">Reserved</i><i className="pool">Usable / DHCP pool</i><i className="broadcast">BC</i></div><div className="address-values"><span>.0</span><span>.1</span><span>.20</span><span>.254</span><span>.255</span></div></div>;
  if(kind==="spectrum"||slug==="pim-finder")return <div className="technical-visual spectrum-tech"><div className="spectrum-axis"><span>frequency</span><i/></div><div className="spectrum-bars">{[42,68,92,55,78,36,64,48].map((h,i)=><i key={i} style={{height:h}}><b>{i%2?"":"CH"}</b></i>)}</div><div className="spectrum-band"><i/><span>selected channel bandwidth</span><i/></div></div>;
  if(kind==="blocks")return <div className="technical-visual grid-tech"><div className="grid-axis y">frequency</div><div className="grid-cells">{Array.from({length:84},(_,i)=><i className={i%14<2?"control":i%17===0?"reference":"data"} key={i}/>)}</div><div className="grid-axis x">time / allocation</div><div className="grid-key"><span><i className="control"/>control</span><span><i className="reference"/>reference</span><span><i className="data"/>available data</span></div></div>;
  return <div className="technical-visual equation-tech"><div><b>{labels[0]}</b><code>01 10 11 00</code></div><i>→</i><div><b>{labels[1]}</b><code>ƒ(x)</code></div><i>→</i><div><b>{labels[2]}</b><code>✓</code></div></div>;
}

export default function ToolExplainer({slug}:{slug:string}){
  const g=guides[slug]??guides["channel-frequency"];
  return <section className="tool-explainer"><div className="explainer-heading"><span className="eyebrow">HOW IT WORKS</span><h2>From inputs to engineering result</h2><p>{g.caption}</p></div>
    <Visual slug={slug} kind={g.visual} labels={g.flow}/>
    <div className="formula-card"><span>FORMULA</span><code>{g.formula}</code><p>{g.caption}</p></div>
    <div className="variable-card"><h3>Variables</h3>{g.variables.map(([symbol,meaning])=><div key={symbol}><code>{symbol}</code><span>{meaning}</span></div>)}</div>
    <div className="steps-card"><h3>Calculation flow</h3>{g.steps.map((s,i)=><div key={s}><b>{i+1}</b><span>{s}</span></div>)}</div>
  </section>;
}
