"use client";

import {useMemo,useState} from "react";
import {domains,releases,snapshot,specifications,technologies,type Domain,type Release,type Technology} from "../data";

export default function SpecificationIndex(){
  const [query,setQuery]=useState("");const [technology,setTechnology]=useState<Technology|"All">("All");const [domain,setDomain]=useState<Domain|"All">("All");const [release,setRelease]=useState<Release|"All">("All");
  const visible=useMemo(()=>specifications.filter(item=>{const text=`${item.number} ${item.title} ${item.summary} ${item.technologies} ${item.domains} ${item.responsibleGroups} ${item.workItems}`.toLowerCase();return (!query.trim()||text.includes(query.trim().toLowerCase()))&&(technology==="All"||item.technologies.includes(technology))&&(domain==="All"||item.domains.includes(domain))&&(release==="All"||item.releaseAvailability.includes(release))}).sort((a,b)=>Number(!a.domains.includes("Radio"))-Number(!b.domains.includes("Radio"))||a.number.localeCompare(b.number)),[query,technology,domain,release]);
  return <section className="gpp-index"><div className="gpp-index-head"><div><span className="eyebrow">SEARCHABLE CATALOGUE</span><h1>3GPP specification index</h1><p>Representative metadata for local review. RAN specifications appear first; architecture, core, security and protocol records remain searchable.</p></div><div><strong>{visible.length}</strong><span>of {specifications.length} sample records</span><small>Snapshot {snapshot.date}</small></div></div>
    <div className="gpp-controls"><label>Search<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Number, title, acronym, group…"/></label><label>Technology<select value={technology} onChange={e=>setTechnology(e.target.value as Technology|"All")}><option>All</option>{technologies.map(x=><option key={x}>{x}</option>)}</select></label><label>Release<select value={release} onChange={e=>setRelease(e.target.value as Release|"All")}><option>All</option>{releases.map(x=><option key={x}>{x}</option>)}</select></label><label>Domain<select value={domain} onChange={e=>setDomain(e.target.value as Domain|"All")}><option>All</option>{domains.map(x=><option key={x}>{x}</option>)}</select></label></div>
    {snapshot.openReleases.includes(release as Release)&&<div className="gpp-warning"><b>{release} remains open.</b> This page shows metadata captured on {snapshot.date}; check the official catalogue for later changes.</div>}
    <div className="gpp-table" role="table" aria-label="3GPP specifications"><div className="gpp-table-row head" role="row"><span>Specification</span><span>Title and scope</span><span>Technology</span><span>Release availability</span></div>{visible.map(item=><a className="gpp-table-row" role="row" href={`/3gpp/spec/${item.number}`} key={item.number}><span><b>{item.type} {item.number}</b><small>{item.responsibleGroups.join(", ")}</small></span><span><b>{item.title}</b><small>{item.summary}</small></span><span>{item.technologies.join(", ")}<small>{item.domains.join(", ")}</small></span><span>{item.releaseAvailability.join(" · ")}</span></a>)}</div>
    {!visible.length&&<div className="gpp-empty"><b>No specifications match these filters.</b><p>Clear one filter or search for another number or term.</p></div>}
  </section>
}
