import type {Metadata} from "next";
import {SiteFrame} from "../../SiteFrame";
import {features,getSpecification,relationships,snapshot,specifications} from "../../data";

type Props={params:Promise<{number:string}>};
export function generateStaticParams(){return specifications.map(item=>({number:item.number}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {number}=await params;const item=getSpecification(number);return {title:item?`${item.type} ${item.number} — WaveKit 3GPP Map`:"Specification not found — WaveKit"}}
export default async function Page({params}:Props){const {number}=await params;const item=getSpecification(number);if(!item)return <SiteFrame><section className="gpp-not-found"><h1>Specification not found</h1><a href="/3gpp/specifications">Return to index</a></section></SiteFrame>;
  const memberships=features.filter(feature=>feature.specifications.includes(item.number));const edges=relationships.filter(edge=>edge.from===item.number||edge.to===item.number);
  return <SiteFrame><section className="gpp-detail"><nav aria-label="Breadcrumb"><a href="/3gpp">3GPP map</a><span>›</span><a href="/3gpp/specifications">Specifications</a><span>›</span><b>{item.type} {item.number}</b></nav><div className="gpp-detail-title"><div><span className="eyebrow">{item.type} · {item.status}</span><h1>{item.number}</h1><h2>{item.title}</h2><p>{item.summary}</p></div><a className="primary" href={item.officialUrl} target="_blank" rel="noreferrer">Open official 3GPP record ↗</a></div>
    <div className="gpp-facts"><article><small>Technology</small><b>{item.technologies.join(", ")}</b></article><article><small>Domain</small><b>{item.domains.join(", ")}</b></article><article><small>Responsible group</small><b>{item.responsibleGroups.join(", ")}</b></article><article><small>Snapshot</small><b>{snapshot.date}</b></article></div>
    <div className="gpp-detail-grid"><section><span className="eyebrow">RELEASE AVAILABILITY</span><h3>Applicable releases</h3><div className="gpp-chips">{item.releaseAvailability.map(release=><span className={snapshot.openReleases.includes(release)?"open":""} key={release}>{release}{snapshot.openReleases.includes(release)?" · open":""}</span>)}</div>{item.releaseAvailability.some(release=>snapshot.openReleases.includes(release))&&<p className="gpp-note">Open-release metadata can change. Verify against the official record after the {snapshot.date} snapshot.</p>}</section><section><span className="eyebrow">CURATED FEATURE LINKS</span><h3>Where this specification appears</h3>{memberships.length?memberships.map(feature=><a className="gpp-membership" href={`/3gpp?release=${feature.release}`} key={feature.id}><b>{feature.name}</b><span>{feature.technology} · {feature.release}</span><small>Inferred grouping · reviewed {snapshot.date}</small></a>):<p>No curated feature membership in this prototype.</p>}</section></div>
    <section className="gpp-relations"><span className="eyebrow">RELATIONSHIP PROVENANCE</span><h3>Connected specifications</h3><div>{edges.length?edges.map(edge=>{const other=edge.from===item.number?edge.to:edge.from;const target=getSpecification(other)!;return <a href={`/3gpp/spec/${other}`} key={`${edge.from}-${edge.to}`}><span className={edge.authority.toLowerCase()}>{edge.authority}</span><b>{target.type} {target.number} · {target.title}</b><small>{edge.kind.replaceAll("-"," ")} · {edge.source}</small>{edge.rationale&&<p>{edge.rationale}</p>}</a>}):<p>No relationship records are included for this specification in the representative prototype.</p>}</div></section>
    <aside className="gpp-disclaimer"><b>Reference-only metadata</b><p>This WaveKit page is not the standard and cannot support a real-life conformity, performance or contractual claim. Consult the current official 3GPP document and applicable regional or vendor requirements.</p></aside>
  </section></SiteFrame>}
