import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

const pages={
  about:{title:"About WaveKit",lead:"A focused browser toolkit for wireless and IP engineering checks.",content:<><h2>What WaveKit is</h2><p>WaveKit Beta 0.1 brings RF planning, cellular, antenna, Wi-Fi and IP calculators into one consistent, searchable workspace. It is designed to make routine checks faster while keeping formulas, assumptions and source standards visible.</p><h2>What it is not</h2><p>WaveKit is not a certified design system, calibrated instrument or substitute for an engineer&apos;s review. The tools produce reference results from the values you enter.</p><h2>Beta feedback</h2><p>This first public version is intentionally transparent. Each calculator includes a technical review panel and a “Report a problem” link that prepares an email containing the tool name and page.</p></>},
  methodology:{title:"Methodology",lead:"How WaveKit selects formulas, communicates limits and reviews technical content.",content:<><h2>Calculation method</h2><p>Calculations run locally in the browser. Standards-based tools implement channel rasters, resource tables, addressing rules or direct equations from the references linked on each page. Planning-estimate tools use simplified engineering models and clearly state the conditions they assume.</p><h2>Status labels</h2><p><b>Standards-based</b> means the tool follows a cited standards convention or table. It does not mean the result is certified. <b>Planning estimate</b> means the output depends on an analytical or simplified model that cannot represent every real deployment.</p><h2>Technical review</h2><p>Every tool shows its model or standard, represented version, applicable range, assumptions and last technical review date. References should be checked again whenever a standard, band plan or regulatory rule changes.</p><h2 id="report-problem">Report a problem</h2><p>Use the report link on the affected tool. Include the shareable URL, expected result, actual result and the standard or source you used for comparison. Do not include confidential network data.</p></>},
  privacy:{title:"Privacy",lead:"WaveKit is designed to perform calculations without an account or server-side calculation service.",content:<><h2>Calculation data</h2><p>Inputs and calculations remain in your browser. Shareable input state is stored in the page URL only when you edit a calculator; anyone who receives that URL can read those values.</p><h2>Data collection</h2><p>WaveKit Beta does not intentionally use accounts, advertising trackers, analytics cookies or a calculation database. The hosting provider may process routine request metadata such as IP address, browser information and request time for security and service operation.</p><h2>External links</h2><p>Standards and reference links open third-party websites with their own privacy practices. Avoid entering sensitive, customer-identifying or production-network information into a URL you plan to share.</p></>},
  disclaimer:{title:"Disclaimer",lead:"WaveKit is reference software, not an engineering approval, compliance certificate or operational guarantee.",content:<><h2>Reference use only</h2><p>Outputs are provided for education, planning estimates and independent cross-checks. They may contain errors, omit site conditions or become outdated as standards, regulations and equipment change.</p><h2>No real-world claim</h2><p>Do not rely on WaveKit as the sole basis for safety decisions, spectrum or regulatory compliance, contractual claims, acceptance testing, commissioning, network changes, purchasing or performance commitments.</p><h2>Your verification responsibility</h2><p>Confirm every material result with current official standards, the applicable regulator, vendor documentation, calibrated measurement tools and a qualified engineer. You remain responsible for inputs, assumptions, interpretation and use of the output.</p><h2>No warranty</h2><p>WaveKit is provided as-is without a warranty of accuracy, completeness, fitness for a particular purpose or uninterrupted availability. To the extent permitted by law, its authors are not liable for loss arising from use of or reliance on the tools.</p></>},
} as const;

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const page=pages[slug as keyof typeof pages];return page?{title:`${page.title} | WaveKit`,description:page.lead}:{title:"Page not found | WaveKit"}}
export default async function InfoPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const page=pages[slug as keyof typeof pages];if(!page)notFound();return <main className="info-page"><header><Link className="brand" href="/"><span className="brand-mark">W</span><span>Wave<span>Kit</span><small>RF ENGINEERING TOOLS</small></span></Link><span className="version-badge">BETA 0.1</span><nav><Link href="/#tools">Tools</Link><Link href="/info/about">About</Link><Link href="/info/methodology">Methodology</Link></nav><Link className="header-cta" href="/">← Home</Link></header><article><div className="breadcrumbs"><Link href="/">Home</Link><i>›</i><b>{page.title}</b></div><span className="eyebrow">WAVEKIT BETA 0.1</span><h1>{page.title}</h1><p className="info-lead">{page.lead}</p><div className="info-content">{page.content}</div><nav className="info-links"><Link href="/info/about">About</Link><Link href="/info/methodology">Methodology</Link><Link href="/info/privacy">Privacy</Link><Link href="/info/disclaimer">Disclaimer</Link></nav></article></main>}
